### ISSUE TITLE
The paper is not available

### ISSUE THREAD

**Issue by GitHubLiwenqi** [xgr19/SAN-for-Traffic-Classification#2]
Hello, I'm very interested in your paper.Could you share your paper on public site ? I'm so sorry that because our univsity does not subscribe to the elsevier journal.

Hope to your reply!

**Comment by CNZZQ1030** [comment]
Hello, author. Is it convenient to provide relevant codes for classification of the latter two data sets? Thank you

**Comment by LongyuanCode** [comment]
> Hello, I'm very interested in your paper.Could you share your paper on public site ? I'm so sorry that because our univsity does not subscribe to the elsevier journal.
> 
> Hope to your reply!

Then the [SciHub](https://tool.yovisun.com/scihub/) is recommanded for you.

**Comment by xgr19** [comment]
> > Hello, I'm very interested in your paper.Could you share your paper on public site ? I'm so sorry that because our univsity does not subscribe to the elsevier journal.
> > Hope to your reply!
> 
> Then the [SciHub](https://tool.yovisun.com/scihub/) is recommanded for you.

Scihub version：https://sci-hub.mobi/10.1016/j.comnet.2021.108267
